### ISSUE TITLE
Rescale favicon.ico to a more reasonable size

### ISSUE THREAD

**Issue by Steve0Greatness** [RedMan13/personal-website#1]
As of currently, the favicon for you website is 606x717 pixels. To my knowledge, no browser displays it that big, meaning it's adding additional loading time for every little reason. I'd suggest scaling it down to a smaller size, such as 38x38 pixels (and filling in empty space with white).

Also, BMP (which is what the favicon is encoded in) is almost entirely uncompressed, so I'd recommend encoding it as an actual icon file instead.

I've basically already done this at https://file.garden/ZVv1LzrahkhXWdWy/godslayerakp.ico

**Comment by RedMan13** [comment]
I don't know of the browser directly supporting any other file format then ico (bmp but with meta)
also, look a the bmp at full res, it's that size for a reason
